# Custom Info
springboot:
  # JWT Info
  jwt:
    secret: certification
  # CoolSMS Info
  coolsms:
    apiKey: aaaa
    secretKey: bbbb
    callingNumber: cccc

spring:
  # DataBase Info
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pesticide
    username: root
    password: k76639950
  # Redis Info
  data:
    redis:
      host: localhost
      port: 8379
      password: a1234567890