# Server Info
server:
  port: 2030

# Spring server Info
spring:
  # Application Info
  application:
    name: certification-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb:///pesticide
    username: 
    password: 
  # Redis Info
  data:
    redis:
      host: 
      port: 
      password: 
  # JPA Info
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: dev
# Eureka Server Info
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http:///eureka
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    ip-address: 
    nonSecurePort: ${server.port}

springboot:
  # JWT Info
  jwt:
    secret: futur-prod-certification
  # CoolSMS Info
  coolsms:
    apiKey: NCS4KURZ0LVGLEUL
    secretKey: V6BVTVPJ6Y9VU5BRMVDHGGQ9ESZ5L7DH
    callingNumber: 01065263863




